version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7-ram
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - DB_CONNECTION: circleci_testing
      - DB_DATABASE: test_sharety

    steps:
      - checkout
      - run: sudo composer self-update --1

      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run dev
      - run: sudo docker-php-ext-install pdo_mysql
      - run: echo "APP_KEY=" > .env.testing
      - run: composer install
      - run: php artisan key:generate
      - run: php artisan migrate
      - run:
          name: php test
          command: vendor/bin/phpunit
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:vO4Wv2s2B8mX7WEXcKu9K0EErQd01KRWBJcCwDWA548"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd sharety && git pull origin main'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
